version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: attendance_pgsql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    ports:
      - "5433:5432"
    volumes:
      - attendance_pgsql:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: attendance_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - attendance_redis:/data

volumes:
  attendance_pgsql:
  attendance_redis: